Datalux/Osintgram

Osintgram.py
=> fix: tagged command

Osintgram.py, main.py
Implementation of `stories` command. Now it is possible to download all types of stories:
- image
- gif
- video
=> feat: add getUserStories command

Osintgram.py, main.py
Change target during a session without restart
=> feat: change target during a session

InstagramAPI.py, Osintgram.py, main.py
=> Little refactoring

Osintgram.py, main.py
=> feat: export results as JSON file

src/Osintgram.py
=> fix: bug #12

main.py, src/Osintgram.py
Feature to set JSON and file output as command options, e.g. `python3 main.py -j <username>` to export commands results as JSON
=> feat: options as arguments

src/Osintgram.py
Avoid relogin using cached credential
=> feat: persistent login

src/Osintgram.py
If target has a private profile but you following target, now you can execute the commands
=> fix: access to profile if you following target

main.py, src/Osintgram.py
Referred to #14.
`wtagged` is a command to get the list of users who tagged target, sorted by photos number.
=> feat: wtagged command

main.py, src/Osintgram.py
Added `fwersemail` command to get emails of target followers
=> feat: added fwersemail command

src/Osintgram.py
=> feat: added follow request options

README.md, doc/COMMANDS.md, main.py, src/Osintgram.py
Added new `fwingsemail` command to get an email list of users followed by target
=> feat: fwingsemail command

src/Osintgram.py
You can set yourself as target
=> feat: set itself as target

src/Osintgram.py
=> Revert "fixed an error while saving non-utf8 followers output"

src/Osintgram.py
=> fix: ConfigurationError bug

src/Osintgram.py
=> fix: show link if challenge_required

src/Osintgram.py
=> fix: KeyError: 'business_email'

src/Osintgram.py
=> fix: login issue

src/Osintgram.py
Fix output limit for `followers`, `followings`, `fwersemail` and `fwingsemail` commands
=> [BUG] some commands output is limited to 100 items

main.py, requirements.txt
This is a fix for running Osintgram on Windows. Actually tab completion may not works
=> [Fix] Windows support

src/Osintgram.py
=> [FIX] lost data collected

main.py
Added is_windows check to the main loop to handle error when running on Windows.
=> Add is_windows check to main loop.

README.md, doc/COMMANDS.md
Just added commentdata to readme and a explanation on Commands file.
=> Commentdata option missing in doc
